In [1]:
import numpy as np
import tensorflow as tf

### Basics

Scalar 就是 Rank-0 Tensor，包含 Single Value。

In [6]:
rank_0_tensor = tf.constant(12)
print(rank_0_tensor)

tf.Tensor(12, shape=(), dtype=int32)


Vector 就是 Rank-1 Tensor，包含 A List of Value。

In [7]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Matrix 就是 Rank-2 Tensor。

In [2]:
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


<img src="img/01/01.png" width="600"/>

建立一個更高維度的 Tensor

In [5]:
rank_3_tensor = tf.constant([
    [
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]
    ],
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]
    ],
    [
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<img src="img/01/02.png" width="600"/>

透過 numpy() Method 將 Tensor 轉為 Numpy Array

In [10]:
rank_3_tensor.numpy()

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)

Tensor 之間基本的數學運算

In [11]:
a = tf.constant([
    [1, 2],
    [4, 5]
])

b = tf.constant([
    [7, 8],
    [11, 12]
])

In [12]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 10],
       [15, 17]], dtype=int32)>

In [13]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 16],
       [44, 60]], dtype=int32)>

In [14]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 32],
       [83, 92]], dtype=int32)>

透過 Tnesor 的 Method 取得 Tensor 的資訊

In [15]:
rank_4_tensor = tf.zeros([3, 2, 2, 4])

In [16]:
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]], shape=(3, 2, 2, 4), dtype=float32)


In [17]:
print("Type: ", rank_4_tensor.dtype)
print("Axes: ", rank_4_tensor.ndim)
print("Shape: ", rank_4_tensor.shape)
print("Number of Elements: ", tf.size(rank_4_tensor).numpy())

Type:  <dtype: 'float32'>
Axes:  4
Shape:  (3, 2, 2, 4)
Number of Elements:  48


### Indexing

可以使用 Python 原始的 Indexing 方法，用於 Tensor 上。基本三原則：
1. 從 0 開始
2. 負數從後面
3. 冒號用法: start:step:stop

In [18]:
rank_1_tensor = tf.constant([0, 1, 2, 3, 4, 5, 7, 11, 30])
print(rank_1_tensor)

tf.Tensor([ 0  1  2  3  4  5  7 11 30], shape=(9,), dtype=int32)


In [19]:
print(rank_1_tensor[0])
print(rank_1_tensor[0:5])
print(rank_1_tensor[-1])

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor(30, shape=(), dtype=int32)


In [20]:
print(rank_2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [3]:
print(rank_2_tensor[0, 1])

tf.Tensor(2, shape=(), dtype=int32)


In [4]:
print(rank_2_tensor[0:3, 0])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [24]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [25]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


<img src="img/01/03.png" width="600"/>

### Manipulate Shape

改變 Tensor 的形狀 (Reshape)，只要 Reshape 前後的 Element 總數相同，Reshape 都可以成功。但是 Reshape 應該只用於「相鄰維度」的 Combine 與 Split

In [32]:
x = tf.ones([3, 2, 4])

print(x)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 2, 4), dtype=float32)


In [33]:
reshaped = tf.reshape(x, [3, 2*4])

print(reshaped)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]], shape=(3, 8), dtype=float32)


使 Tensor 變成 1 維 (Flatten)

In [34]:
flatten = tf.reshape(x, [-1])

print(flatten)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(24,), dtype=float32)


### DTypes

在建立 Tensor 時可以指定其 dtype，也可以透過 tf.cast() 改變其 dtype

In [35]:
float64_tensor = tf.constant([
    [1.2, 2.2, 3.4]
], dtype=tf.float64)

print(float64_tensor)

uint8_tensor = tf.cast(float64_tensor, dtype=tf.uint8)

print(uint8_tensor)

tf.Tensor([[1.2 2.2 3.4]], shape=(1, 3), dtype=float64)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=uint8)


### Broadcasting

與 Numpy 中的 Broadcasting 一樣，兩個 Tensor 在進行某些操作時，形狀/維度小的 Tensor 會被擴大成形狀/維度大的 Tensor

In [36]:
x = tf.constant([1, 2, 3, 4])
y = 1
print(x+y)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [38]:
x = tf.constant([
    [1],
    [2],
    [3]
])

y = tf.constant([
    [1, 2, 3, 4]
])

print(x * y)

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<img src="img/01/04.png" width="600"/>

### Ragged Tensor

TensorFlow 中存在 Ragged Tensor：在同一個維度(軸)中的元素數量不一致

In [39]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]
]

RaggedTensor 的建立方法與一般 Tensor 不同

In [40]:
tf.constant(ragged_list)

ValueError: Can't convert non-rectangular Python sequence to Tensor.

In [41]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


### String Tensor

TensorFlow 也支援將 String 作為 Tensor 中的元素。String 的長度不影響 Tensor 的維度

In [43]:
scalar_string_tensor = tf.constant("Hello Wolrd")
print(scalar_string_tensor)

tf.Tensor(b'Hello Wolrd', shape=(), dtype=string)


In [45]:
tensor_of_strings = tf.constant(["Hello World", "Hello Enya", "Hello Johnny"])
print(tensor_of_strings)

tf.Tensor([b'Hello World' b'Hello Enya' b'Hello Johnny'], shape=(3,), dtype=string)


也可以將 Tensor 中的每一個 String 進行 Split，形成一個新的 RaggedTensor

In [49]:
tf.strings.split(tensor_of_strings, sep=" ")

<tf.RaggedTensor [[b'Hello', b'World'], [b'Hello', b'Enya'], [b'Hello', b'Johnny']]>

### Sparse Tensor

TensorFlow 也支援 SparseTensor：假設 Tensor 中的數值很稀疏，就可以透過 SparseTensor 使其更有效率的備存在記憶體中

In [50]:
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]],
    values=[1, 2],
    dense_shape=[3, 4]
)

In [51]:
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


將 SparseTensor 轉為一般 Tensor

In [52]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]], dtype=int32)>