In [1]:
import tensorflow as tf

### Create Variable

tf.Variable 是 TensorFlow 中特別的 Tensor，此 Tensor 中的數值可以改變。tf.keras 就是透過 tf.Variable 存放模型的參數。

實際上，tf.Variable 底層仍是由 tf.Tensor 實作！

In [2]:
my_tensor = tf.constant([
    [1, 2],
    [3, 4]
])

my_variable = tf.Variable(my_tensor)

In [3]:
print(my_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [4]:
print(my_variable.shape)
print(my_variable.dtype)
print(my_variable.numpy())

(2, 2)
<dtype: 'int32'>
[[1 2]
 [3 4]]


tf.Variable 無法 Reshape；若進行 Reshape，會產生新的 Tensor

In [5]:
tf.reshape(my_variable, [-1])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

可以透過 tf.Variable.assign 改變 tf.Variable 的數值，但是 Shape 必須相同！

In [6]:
a = tf.Variable([1, 2, 3])
print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [7]:
a.assign([4, 5, 6])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [8]:
print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


利用已經存在的 tf.Variable 建立一個新的 tf.Variable 時為 Deep Copy => 兩者不影響

In [9]:
b = tf.Variable(a)
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


In [10]:
b.assign_add([1, 1, 1])
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([5, 6, 7], dtype=int32)>


In [11]:
c = a

In [12]:
print(c)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


但是如果透過 "=" 將已經建立的 tf.Variable Assign 給另外一個 tf.Variable 為 Shallow Copy => 互相影響

In [13]:
c.assign_sub([1, 1, 1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

In [14]:
a

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

### Variable Lifecycle

在 Python-based 的 TensorFlow 中，tf.Variable 的生命週期與 Python 中的變數一樣。當 tf.Variable 沒有被任何 Reference 時，就會被 Deallocate。

### Variable Name

tf.Variable 可以有 Name，即使兩個 tf.Variable 有相同的 Name，但是仍是 Backed By 不同的 Tensor。

In [15]:
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

In [16]:
a = tf.Variable(tensor, name="Johnny")
b = tf.Variable(tensor, name="Johnny")